server:
  port: 8001

spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myproject?characterEncoding=utf-8&useSSL=false
    username: root
    password: wly10033
